Budget_Tracker/Models/Budgets.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Budget_Tracker.Models
{
    public class Budgets
    {
        public Guid ID { get; set; }

        [ForeignKey("ApplicationUsers")]
        public string User { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Name must be shorter than 30 characters")]
        public string Name { get; set; }

        [Required]
        [Range(0, Double.MaxValue, ErrorMessage = "Amount must be positive number")]
        public double Amount { get; set; }

        [StringLength(100, ErrorMessage = "Descriptions must be shorter than 100 characters")]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }
    }
}

Budget_Tracker/Controllers/BudgetCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Budget_Tracker.Data;
using Budget_Tracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace Budget_Tracker.Views
{
    public class BudgetCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BudgetCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = SD.User + "," + SD.Admin)]
        // GET: BudgetCategories
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BudgetCategories.Include(b => b.Budget);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BudgetCategories/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budgetCategories = await _context.BudgetCategories
                .Include(b => b.Budget)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (budgetCategories == null)
            {
                return NotFound();
            }

            return View(budgetCategories);
        }

        // GET: BudgetCategories/Create
        public IActionResult Create()
        {
            var fullList = _context.Budgets;
            List<Budgets> userList = new List<Budgets>();

            foreach (var item in fullList)
            {
                if (User.IsInRole(SD.Admin))
                {
                    userList.Add(item);
                }
                else if (item.User == HttpContext.User.Identity.Name)
                {
                    userList.Add(item);
                }
            }

            ViewData["BudgetID"] = new SelectList(userList, "ID", "Name");
            return View();
        }

        // POST: BudgetCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,User,Name,Amount,Description,BudgetID")] BudgetCategories budgetCategories)
        {
            if (ModelState.IsValid)
            {
                budgetCategories.ID = Guid.NewGuid();
                budgetCategories.User = HttpContext.User.Identity.Name;
                _context.Add(budgetCategories);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BudgetID"] = new SelectList(_context.Budgets, "ID", "Name", budgetCategories.BudgetID);
            return View(budgetCategories);
        }

        // GET: BudgetCategories/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budgetCategories = await _context.BudgetCategories.FindAsync(id);
            if (budgetCategories == null)
            {
                return NotFound();
            }
            var fullList = _context.Budgets;
            List<Budgets> userList = new List<Budgets>();
            foreach (var item in fullList)
            {
                if (User.IsInRole(SD.Admin))
                {
                    userList.Add(item);
                }
                else if (item.User == HttpContext.User.Identity.Name)
                {
                    userList.Add(item);
                }
            }
            ViewData["BudgetID"] = new SelectList(userList, "ID", "Name", budgetCategories.BudgetID);
            return View(budgetCategories);
        }

        // POST: BudgetCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,User,Name,Amount,Description,BudgetID")] BudgetCategories budgetCategories)
        {
            if (id != budgetCategories.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(budgetCategories);
                    budgetCategories.User = HttpContext.User.Identity.Name;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BudgetCategoriesExists(budgetCategories.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BudgetID"] = new SelectList(_context.Budgets, "ID", "Name", budgetCategories.BudgetID);
            return View(budgetCategories);
        }

        // GET: BudgetCategories/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budgetCategories = await _context.BudgetCategories
                .Include(b => b.Budget)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (budgetCategories == null)
            {
                return NotFound();
            }

            return View(budgetCategories);
        }

        // POST: BudgetCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var budgetCategories = await _context.BudgetCategories.FindAsync(id);
            _context.BudgetCategories.Remove(budgetCategories);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BudgetCategoriesExists(Guid id)
        {
            return _context.BudgetCategories.Any(e => e.ID == id);
        }

        public async Task<IActionResult> Report(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            BudgetsAndExpensesVM vm = new BudgetsAndExpensesVM();
            vm.expenses = _context.Expenses.ToList();
            vm.budgetCategories = _context.BudgetCategories.ToList();
            vm.budgets = _context.Budgets.ToList();

            BudgetsAndExpensesVM actualList = new BudgetsAndExpensesVM();

            List<BudgetCategories> actualBC = new List<BudgetCategories>();

            foreach (var item in vm.budgetCategories)
            {
                if (item.ID == id)
                {
                    actualBC.Add(item);
                }
            }

            List<Expenses> actualExpense = new List<Expenses>();


            foreach (var item in vm.expenses)
            {
                if (item.BudgetCategoryID == id)
                {
                    actualExpense.Add(item);
                }
            }

            
            actualList.budgetCategories = actualBC;
            actualList.expenses = actualExpense;


            if (actualList == null)
            {
                return NotFound();
            }

            return View(actualList);
        }
    }
}

Budget_Tracker/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Budget_Tracker.Data;
using Budget_Tracker.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Budget_Tracker.Views
{
    public class BudgetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BudgetsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = SD.User + "," + SD.Admin)]
        // GET: Budgets
        public async Task<IActionResult> Index()
        {
            return View(await _context.Budgets.ToListAsync());
        }

        // GET: Budgets/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budgets = await _context.Budgets.FirstOrDefaultAsync(m => m.ID == id);
            if (budgets == null)
            {
                return NotFound();
            }

            return View(budgets);
        }

        // GET: Budgets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,User,Name,Amount,Description,StartDate,EndDate")] Budgets budgets)
        {
            if (ModelState.IsValid)
            {
                budgets.ID = Guid.NewGuid();
                budgets.User = HttpContext.User.Identity.Name;
                _context.Add(budgets);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(budgets);
        }

        // GET: Budgets/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budgets = await _context.Budgets.FindAsync(id);
            if (budgets == null)
            {
                return NotFound();
            }
            return View(budgets);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,User,Name,Amount,Description,StartDate,EndDate")] Budgets budgets)
        {
            if (id != budgets.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(budgets);
                    budgets.User = HttpContext.User.Identity.Name;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BudgetsExists(budgets.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(budgets);
        }

        // GET: Budgets/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budgets = await _context.Budgets
                .FirstOrDefaultAsync(m => m.ID == id);
            if (budgets == null)
            {
                return NotFound();
            }

            return View(budgets);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var budgets = await _context.Budgets.FindAsync(id);
            _context.Budgets.Remove(budgets);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BudgetsExists(Guid id)
        {
            return _context.Budgets.Any(e => e.ID == id);
        }

        public async Task<IActionResult> Report(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            BudgetsAndExpensesVM vm = new BudgetsAndExpensesVM();
            vm.expenses = _context.Expenses.ToList();
            vm.budgetCategories = _context.BudgetCategories.ToList();
            vm.budgets = _context.Budgets.ToList();

            BudgetsAndExpensesVM actualList = new BudgetsAndExpensesVM();

            List<Budgets> actualBudget = new List<Budgets>();

            foreach(var item in vm.budgets)
            {
                if(item.ID == id)
                {
                    actualBudget.Add(item);
                }
            }

            List<BudgetCategories> actualBC = new List<BudgetCategories>();


            foreach (var item in vm.budgetCategories)
            {
                if (item.BudgetID == id)
                {
                    actualBC.Add(item);
                }
            }

            actualList.budgets = actualBudget;
            actualList.budgetCategories = actualBC;


            if (actualList == null)
            {
                return NotFound();
            }

            return View (actualList);
        }
    }
}

Budget_Tracker/Views/Budgets/Create.cshtml
@model Budget_Tracker.Models.Budgets

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Budgets</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Budget_Tracker/Views/Budgets/Delete.cshtml
@model Budget_Tracker.Models.Budgets

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Budgets</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Budget_Tracker/Views/Budgets/Details.cshtml
@model Budget_Tracker.Models.Budgets

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Budgets</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Budget_Tracker/Views/Budgets/Edit.cshtml
@model Budget_Tracker.Models.Budgets

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Budgets</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Budget_Tracker/Views/Budgets/Index.cshtml
@model IEnumerable<Budget_Tracker.Models.Budgets>

@{
    ViewData["Title"] = "Index";
}

<h1>Budgets</h1>

<p>
    <a class="btn btn-outline-info" asp-action="Create">Create New <i class="far fa-plus-square"></i></a>
</p>
<table class="table" id="budgetTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
    if (User.IsInRole(SD.Admin) || User.Identity.Name == item.User)
    {
        <tr>
            <td>
                <a class="btn btn-outline-info btn-sm" asp-action="Report" asp-route-id="@item.ID"> @Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                <a class="btn btn-outline-info btn-sm" asp-action="Edit" asp-route-id="@item.ID">Edit <i class="far fa-edit"></i></a>
                <a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@item.ID">Details <i class="far fa-file-alt"></i></a>
                <a class="btn btn-outline-info btn-sm" asp-action="Delete" asp-route-id="@item.ID">Delete <i class="far fa-trash-alt"></i></a>
            </td>
        </tr>
    }
}
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#budgetTable').DataTable();
    });
</script>

Budget_Tracker/Views/Budgets/Report.cshtml
@model BudgetsAndExpensesVM



<h1>Budget: @Model.budgets.ElementAt(0).Name</h1>

@{
    double categoriesTotal = 0;


    @foreach (var item in Model.budgetCategories)
    {
        categoriesTotal += item.Amount;
    }

    categoriesTotal = Math.Round(categoriesTotal, 2);

    double surplus = Model.budgets.ElementAt(0).Amount - categoriesTotal;
}

<h5>Budget amount: $@Model.budgets.ElementAt(0).Amount</h5>
<h5>Sum of categories: $@categoriesTotal</h5>

@if (@surplus >= 0)
    {
        <h5>Surplus: $@Math.Round(surplus, 2)</h5>
    }
else
    {
        <h5>Deficit: $@Math.Round(surplus, 2)</h5>
    }


<p>
    <a class="btn btn-outline-info" asp-controller="BudgetCategories" asp-action="Create">Create New <i class="far fa-plus-square"></i></a>
</p>
<table class="table" id="budgetCatTable">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Amount
            </th>
            <th>
                Description
            </th>
            <th>
                Budget
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.budgetCategories)
        {
            if (item.Budget.User == User.Identity.Name || User.IsInRole(SD.Admin))
            {
                <tr>
                    <td>
                        <a class="btn btn-outline-info btn-sm" asp-controller="BudgetCategories" asp-action="Report" asp-route-id="@item.ID"> @Html.DisplayFor(modelItem => item.Name)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Budget.Name)
                    </td>
                    <td>
                        <a class="btn btn-outline-info btn-sm" asp-controller="BudgetCategories" asp-action="Edit" asp-route-id="@item.ID">Edit <i class="far fa-edit"></i></a>
                        <a class="btn btn-outline-info btn-sm" asp-controller="BudgetCategories" asp-action="Details" asp-route-id="@item.ID">Details <i class="far fa-file-alt"></i></a>
                        <a class="btn btn-outline-info btn-sm" asp-controller="BudgetCategories" asp-action="Delete" asp-route-id="@item.ID">Delete <i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#budgetCatTable').DataTable();
    });
</script>